config/routes.rb
HelloSignDemo::Application.routes.draw do
  get "embedded/signing"
  get "embedded/requesting"
  get "embedded/template_requesting"
  get "embedded/oauth_demo"
  get "home/index"

  post 'embedded/signing', to: 'embedded#create_signing'
  post 'embedded/requesting', to: 'embedded#create_requesting'
  post 'embedded/template_requesting', to: 'embedded#create_template_requesting'
  post 'embedded/oauth_demo', to: 'embedded#create_oauth_demo'

  root 'home#index'

  post 'oauth', to:'oauth#index'
  get 'oauth', to:'oauth#index'
  post 'callback', to: 'home#callback'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/embedded_controller.rb
class EmbeddedController < ApplicationController
  def signing
  end

  def create_signing
    begin
      embedded_request = HelloSign.create_embedded_signature_request(
        :test_mode => 1,
        :title => 'NDA with Acme Co.',
        :subject => 'The NDA we talked about',
        :message => 'Please sign this NDA and then we can discuss more. Let me know if you have any questions.',
        :signers => [{
            :email_address => params[:email],
            :name => params[:name]
          }
        ],
        :file_urls => PDF_FILE
      )

      signature_id = embedded_request.signatures[0].signature_id

      embedded = HelloSign.get_embedded_sign_url :signature_id => signature_id
      @sign_url = embedded.sign_url
      render 'signing'
    rescue => e
      render :text => e
    end
  end

  def requesting
  end

  def create_requesting
    begin
      data = {
        :test_mode => 1,
        :type => "request_signature",
        :subject => "Embedded Signature Request",
        :requester_email_address => "testuser@example.com",
        :message => "This is the message that goes along with your request."
      }

      if params[:requester_email_address]
        data[:requester_email_address] = params[:requester_email_address]
      end

      data[:files] = params[:files]

      resp = HelloSign.create_embedded_unclaimed_draft data
      claim_url = resp.claim_url;

      @sign_url = claim_url
      render 'requesting'
    rescue => e
      render :text => e
    end
  end

  def template_requesting
    @templates = HelloSign.get_templates(:page => 1)
    @data = (@templates.map {|t| t.data }).to_json
  end

  def create_template_requesting
    signers = []
    params[:signers].each_with_index do |signer, index|
      signer[1][:role] = signer[0]
      signers << signer[1]
    end
    ccs = []
    params[:ccs].each_with_index do |cc, index|
      cc[1][:role] = cc[0]
      ccs << cc[1]
    end
    begin
      request = HelloSign.create_embedded_signature_request_with_reusable_form(
        :test_mode => 1,
        :reusable_form_id => params[:template],
        :title => 'Purchase Order',
        :subject => 'Purchase Order',
        :message => 'Glad we could come to an agreement.',
        :signers => signers,
        :ccs => ccs,
        :custom_fields => params[:custom_fields]
      )
      signature_id = request.signatures[0].signature_id

      embedded = HelloSign.get_embedded_sign_url :signature_id => signature_id
      @sign_url = embedded.sign_url
      render 'template_requesting'
    rescue => e
      render :text => e
    end
  end

  def oauth_demo
  end

  def create_oauth_demo
    begin
      if cookies[:access_token]
        client = HelloSign::Client.new :auth_token => cookies[:access_token]
      else
        raise 'do not have auth token yet'
      end
      #make sure it not use config account
      client.email_address = nil
      client.password = nil

      request = client.send_signature_request(
        :test_mode => 1,
        :title => 'NDA with Acme Co.',
        :subject => 'The NDA we talked about',
        :message => 'Please sign this NDA and then we can discuss more. Let me know if you have any questions.',
        :signers => [{
            :email_address => params[:email],
            :name => params[:name],
          }
        ],
        :file_urls => PDF_FILE
      )
      flash[:notice] = "Sent Signature Request to #{params[:email]} successful"
      render 'oauth_demo'
    rescue => e
      render :text => e
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @account = HelloSign.get_account
  end

  def callback
    render :text => 'Hello API Event Received'
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def index
    @auth = HelloSign.get_oauth_token(:state => params[:state], :code => params[:code])
    cookies[:access_token] = @auth["access_token"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/embedded_helper.rb
module EmbeddedHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/views/embedded/_embedded_view.html.slim
script type="text/javascript" src="//s3.amazonaws.com/cdn.hellofax.com/js/embedded.js"
javascript:
  HelloSign.init("#{HelloSign.client_id}");
  HelloSign.open({
      url: "#{raw @sign_url}",
      allowCancel: true,
      skipDomainVerification: true,
      messageListener: function(eventData) {
          //  do something
      }
  });

app/views/embedded/oauth_demo.html.slim
h1 Embedded Signing Demo

.embeddedSigning
  p.intro This page demonstrates how you can add an embedded signature request to your Ruby-based web application.
  br/

  .part
    h2 Try it out
    p Please sign our NDA.

    = form_tag('oauth_demo', :method => :POST, :html => {:class => 'form-horizontal'})
      input type='text' name='name' class='form-control' placeholder='Signer name'
      input type='email' name='email' class='form-control' placeholder='Signer email'
      br/
      br/
      input class="btn btn-primary" id="startButton" type="submit" value="Launch Demo"

- if @sign_url
  = render 'embedded_view'

javascript:

  $("#startButton").click(function() {
      // Request an OAuth token from HelloSign
      var win = window.open(
              "#{raw HelloSign.oauth_url('hellosign-ruby')}",
              "hellosign_oauth",
              "width=600,height=400");

      // Poll window to see if it's closed
      var pollTimer = setInterval(function() {
          if (win.closed !== false) {
              // Cancel the polling
              window.clearInterval(pollTimer);

              // Assume we have authorization and submit
              // the form to create the signature request
              $('form').trigger("submit");
          }
      }, 200);
      return false;
  });

app/views/embedded/requesting.html.slim
h1 Embedded Request Demo
.embeddedSigning
  p.intro Request signatures for documents directly from your website with HelloSign's embedded request capability.\
  br/

  
  .part
    h2 Try it out

    = form_tag('requesting', :method => :POST, :multipart => true, :class => 'form-horizontal')
      .control-group
        label.control-label for='files[]' File
        .controls
          input multiple="multiple" name="files[]" type="file"

      .control-group
        label.control-label for='requester_email_address' Your email
        .controls
          input type='email' name='requester_email_address' placeholder='Your email'
      br/

      .control-group
        .span4
        input class="btn btn-primary" id="startButton" type="submit" value="Launch Demo"

- if @sign_url
  = render 'embedded_view'

app/views/embedded/signing.html.slim
h1 Embedded Signing Demo #{@sign_url}
.embeddedSigning
  p.intro  This page demonstrates how you can add an embedded signature request to your Ruby-based web application.
  br/

  .part
    h2 Try it out
    p Please sign our NDA.

    = form_tag('signing', :method => :POST, :html => {:class => 'form-horizontal'})
      input type='text' name='name' class='form-control' placeholder='Your name'
      input type='email' name='email' class='form-control' placeholder='Your email'
      br/
      br/
      input class="btn btn-primary" id="startButton" type="submit" value="Launch Demo"

- if @sign_url
  = render 'embedded_view'

app/views/embedded/template_requesting.html.slim
javascript:

  function initTemplates() {
    var templates = #{raw @data}
    var templateFields = $("#templateFields");
    templateFields.hide();
    $("#startButton").hide();
    var selectList = $("#templates");
    for (var i = 0; i < templates.length; i++) {
      selectList.append('<option value="' + templates[i].reusable_form_id + '" data-id="' + i + '">' + templates[i].title + '</option>');
    }
    selectList.change(function(e) {
      templateFields.show();
      $('#signersContainer').empty();
      $('#ccsContainer').empty();
      $('#customFieldsContainer').empty();
      var template = templates[$("option:selected", this).attr("data-id")];
      if (template) {
        for (var i = 0; i < template.signer_roles.length; i++) {
          var signerRole = template.signer_roles[i];
          var newOptionStr = '<label for="signerRole_' + signerRole.name + '">' + (signerRole.order != null ? signerRole.order + " " : '') +
          signerRole.name + ':</label>&nbsp;<input type="text" name="signers['+ signerRole.name + '][email_address]" placeholder="Email address"/> ' +
          '<input type="text" name="signers[' + signerRole.name + '][name]" placeholder="Name"/><br />';
        var newSignerFields = $(newOptionStr);
          $('#signersContainer').append(newSignerFields);
        }
        for (var i = 0; i < template.cc_roles.length; i++) {
          var ccRole = template.cc_roles[i].name;
          var newCCFieldStr = '<label for="ccRole_' + ccRole + '">' + ccRole + ':</label>&nbsp;<input type="text" name="ccs[' +
            ccRole + '][email_address]" placeholder="Email address"/><br />'
          var newCCFields = $(newCCFieldStr);
          $('#ccsContainer').append(newCCFields);
        }
        for (var i = 0; i < template.custom_fields.length; i++) {
          var cf = template.custom_fields[i];
          var newCFFieldStr = '<label for="custom_fields[' + cf.name + ']">' + cf.name + ':</label>&nbsp;<input type="text" name="custom_fields[' + cf.name + ']" placeholder="' +
            cf.type + '"/><br />';
          var newCFField = $(newCFFieldStr);
          $('#customFieldsContainer').append(newCFField);
        }
        $('#templateId').val(template.reusable_form_id);
        $('#startButton').show();
      } else {
        $('#templateFields').hide();
        $('#startButton').hide();
      }
    });
  };
  $(document).ready(function(){
      initTemplates();
  });

h1 Embedded Request Demo
.embeddedSigning
  p.intro Request signatures for documents directly from your website with HelloSign's embedded request capability.
  br/


  .part
    h2 Try it out

    = form_tag('template_requesting', :method => :POST, :class => 'form-horizontal')
      .control-group
        label.control-label for='files[]' File
        .controls
          select#templates name="template"
            option selected=true Choose a template ...
        #templateFields
          h3 Template Details
          fieldset#signers
            legend Signers
            #signersContainer
          fieldset#ccs
            legend Carbon copy
            #ccsContainer
          fieldset#customFields
            legend Custom Fields
            #customFieldsContainer

      .control-group
        .span4
        input class="btn btn-primary" id="startButton" type="submit" value="Launch Demo"

- if @sign_url
  = render 'embedded_view'

app/views/home/index.html.slim
h1 HelloSign Ruby Samples

span You may be interested in the following:

ul
  li= link_to 'Embedded Signing', embedded_signing_path
  li= link_to 'Embedded Requesting', embedded_requesting_path
  li= link_to 'Embedded Requesting from a Template', embedded_template_requesting_path
  li= link_to 'OAuth Demo', embedded_oauth_demo_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "HelloSignDemo"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-fluid-top
      .navbar-inner#header
        .container-fluid
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#{root_path}"
            = image_tag "logo.png"
          .container-fluid.nav-collapse
            h3 DEVELOPERS

    .container-fluid.main-container
      .row-fluid
        .span9
          = bootstrap_flash
          = yield

      footer

app/views/oauth/index.html.slim
| Hello API Event Received

javascript:
  window.close();